### ISSUE TITLE
Set up an azure web app backed dev instance of wiki

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcpedia#152]
A test / dev instance using azure managed web apps and mysql / mariadb to make sure issues such as the azure files + apache on ubuntu one will not re-appear.

**Comment by LecCory** [comment]
Following steps outlined in this article: 

[Moving a wiki](https://www.mediawiki.org/wiki/Manual:Moving_a_wiki)

1. Make Backup of your wiki
    - [x] Database backup -  **Pulled SQL dump from storage**
2. Backup Filesystem data
    - [ ]  File System backup - **Where/how would I go about capturing file system data required for this step?**
3. Transfer backups to new server
   - [ ] Blocked by steps 1 and 2
4. Restore data from backups
   - [ ] Blocked by steps 1,2 and 3


Requirements for this would be: 


![Image](https://user-images.githubusercontent.com/17506947/213275682-22b1b2b3-f4aa-483e-9e7f-62aaa78dece6.png)


Scenario: [Web app private connectivity to Azure SQL Database](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/private-web-app/private-web-app)
- App Service Plan
   - Web App with PHP 8.1 as runtime
- Database Service
   - Per IMTD requirements MSSQL is currently one of the only supported DBs
   - Postgres is another option but it comes with certain caveats (Where Postgres can be hosted and commitment to support)
- Virtual Network
   - A virtual network with at least 2 subnets (App service and database service) should be created
- Private Endpoints
  - To ensure that the database isn't public facing and exposed to the Internet, private endpoint for the database service will need to be configured to allow communication between the Web App and the Database. 
  - Private DNS zone will need to be configured along with the private endpoint


In development, I created a new web app under an existing App service Plan and at minimum could access the config page for a new setup of Mediawiki. I haven't created a database back end because the conversation leads back to what database engine are we able to run in the GCX tenant. I would like to continue testing but I would need some guidance and/or assistance on capturing filesystem data from wherever the server is hosted.

**Comment by LecCory** [comment]
I believe in Azure if you setup a fileshare there's scripts you can run to mount the share as a drive. I've been doing work on other projects to extract data out of storage accounts so I'd like to take a stab at this. Since there's quite a few storage accounts and resource groups in the collab tenant could you provide me with the resources used for wiki, @Phanoix ?

**Comment by LecCory** [comment]
For my own sanity, @piet0024 are we looking to move GcWiki or GCPedia or both, we seem to be talking about GCPedia in our meetings, but this request is for GCWiki. 

My understanding and correct me if I'm wrong, but GCWiki is our public facing MediaWiki instance, part of our GCCollab suite of tools and GCPedia is our internal tool accessible only from GC subnets?

I simply want to make sure that the instance I'm targeting to extract data from is the right instance and not exposing data from the instance that is behind GC firewalls.

With that said, I'm going to begin working on implementing Microsoft recommended security baseline on our Cypher PGSQL resource. 
[Azure security baseline for Azure Database for PostgreSQL](https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/postgresql-security-baseline)

I am also using the same instance to work as our collab backend

**Comment by piet0024** [comment]
Yes, @LecCory you are correct with GCpedia being internal (only available to GC subnets) and GCwiki being the external. We would like to move both at some point, but I would like us to focus on GCpedia (internal) first. We will look to move GCwiki in the future.

**Comment by LecCory** [comment]
A fresh installation of wiki media has been installed in Cypher using the architected solution above, with private endpoints and postgres PaaS. 

https://dgcx-wiki.azurewebsites.net

No gcpedia or wiki data has been moved, however.

**Comment by nschonni** [comment]
Not sure if you meant that the private endpoints was just supposed to be accessible only from the GCNet, but i'm able to access that from my home machine

**Comment by LecCory** [comment]
Hi Nick, thanks for testing out the site. Yes, in this current PoC state it is publicly accessible. The private endpoints are configured on the outgoing leg of the web app so it ensures that communication with the database stays within the configured virtual network and does not go outside. This also ensures that the database itself is not public facing as well. 
In production we would ensure that the web app is behind the proper TBS security appliances so access is limited to GCNet only. I have updated drawings demonstrating the access flow with the TBS appliances, however I didn't want to post them on a publicly accessible forum. I am also with the Treasury Board so I'd be happy to have a sidebar meeting with you to share them with you if you'd like.

**Comment by nschonni** [comment]
Not a problem, I was just checking that it wasn't accidentally publicly exposed via a route/blocking issue for my home machine, even though there is no content.
I think we'll be talking to your team in the future, just to figure out the tools landscape going forward
