### ISSUE TITLE
Upgrade to Mediawiki 1.40

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcpedia#158]
Upgrade core, start repo from scratch and structure GCpedia repo similar to how GCwiki is structured for upgrading in the future.

**Comment by Phanoix** [comment]
The plan is:
 * update external wiki to latest stable MW - currently 1.40
 * carry over any extensions needed for gcpedia and the modified skin + evaluate merging any core changes in the same way they're currently handled for external wiki (only the changed files are kept in the repo)

**Comment by Phanoix** [comment]
gcpedia customizations not related to or different from external wiki:
 * skin - custom vector skin
 * maintenance
   * categorization bot
   * docker / dev install script - will need to merge the two toggleable by env variable

**Comment by Phanoix** [comment]
remaining parts:
### external wiki
 - [ ] language files update, or better yet find a better way to apply our changes without touching the core language files. We already have a extension for that but it will need to be able to work for both gcpedia and the external wiki, like a config / setting variable that toggles between the two.
 - [ ] Favourites extension - it's not supported and broken in mw 1.40, either drop it or fix it
 - [ ] tree and menu extension - looks like it can be pulled in from upstream, check if there are any modifications, etc. reasons why we can't first. otherwise it seems to work in 1.40
### gcpedia - specific
 - [ ] extensions that are not already handled and updated as part of the external wiki update, may need to drop / update / swap to submodules of upstream as appropriate
 - [ ] gcpedia flavour of the vector skin
 - [ ] code / includes changes - ideally we can not have them as core changes or not have some at all if no longer relevant
 - [ ] anything else needed to differentiate between the two instances, such as the dev environment / docker install script, support for both types of PR review instances, and anything else I may be forgetting.
