### ISSUE TITLE
GCpedia - default environment in IMTD dev environment

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcpedia#185]

**Comment by piet0024** [comment]
#216 related

**Comment by Phanoix** [comment]
app-wise:
these extensions no longer work in 1.40/41 because the parser option they depended on got removed:
https://github.com/gctools-outilsgc/gcpedia/tree/main/extensions/MagicNoNumberedHeadings
https://github.com/gctools-outilsgc/gcpedia/tree/main/extensions/MagicNumberedHeadings

to go with the db update, the show editors extension will need to have its "editings" table dropped and re-generated with update.php since it doesn't seem to have a migration script at least in the latest version
https://www.mediawiki.org/wiki/Extension:AjaxShowEditors

**Comment by Phanoix** [comment]
for the environment: 
1. will need to figure out a way to install a few packages such a memcached as in the init script in an environment where the regular apt install method is blocked https://github.com/gctools-outilsgc/gcpedia/blob/main/.azure/env-init.sh
2. will have to test and perhaps change how uploaded files in a mounted images directory are handled during a deployment, having them all deleted every time code is deployed because that's what azure thinks we want would not be ideal.

**Comment by piet0024** [comment]
Scope of this issue was for Azure web app support, path forward is to update software and OS in current VM environment.
