### ISSUE TITLE
Extend login session duration to more than one day

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gcpedia#54]
Hi,

Each day, I need to log in again in GCpedia. The login session duration should be extended.

What about aligning the settings with GCconnex?

Thanks!

**Comment by ToferC** [comment]
Hi @Phanoix - I thought both GCpedia and GCconnex were set to 6 month tokens. If so, please comment and close.

**Comment by Phanoix** [comment]
The issue is likely because of the simplified signon which does change things up, but if you log in to GCpedia regularly and check remember me it should last quite a while.

**Comment by gabrielcossette** [comment]
This is occuring using the "Simplified Sign-on" option.

Since I migrated to the Simpligied Sign-on, I can't test with the regular login. However, it seems to be only a 1 day token as it specifically says on the login page "Remember my login on this browser (for a maximum of 1 days)".

In my case, GCconnex is more than 1 day but not GCpedia.

**Comment by massierick** [comment]
I am having the same occurrence with simplified sign on each day. Actually, it seems like it might happen every time I fully close the browser or log off the computer. But luckily, it's just one click to sign back in, so it's not nearly as inconvenient as it could be if I had to retype username and password.

**Comment by Phanoix** [comment]
We'll see if we run into the same issue with using account.gccollab.ca for signon, wiki.gccollab.ca already uses it so if that's still a problem this can be re-opened.
